package com.aki.androidbpcode.datahandeling.dataclass

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "FarmerInfo")
data class FarmerInfo(
    val bank_CODE: String? = null,
    val brnch_CODE: String? = null,
    val caste_CODE: String? = null,
    val city: String? = null,
    val cntry_CODE: String? = null,
    val comp_CODE: String? = null,
    val crp_LOAN_AC: String? = null,
    val crtd_BY: String? = null,
    val crtd_DT: String? = null,
    val delivery_POINT: String? = null,
    val delivery_TYPE: String? = null,
    val ex_SERVICE_YN: String? = null,
    val fa_BANK_CODE: String? = null,
    val family_TYPE: String? = null,
    @PrimaryKey
    val farmerId: Int,
    val farmerName: String? = null,
    val fth_HUS_NAME: String? = null,
    val gender: String? = null,
    val gl_CODE: String? = null,
    val govt_GROWER_CODE: String? = null,
    val grower_CATG: String? = null,
    val grower_CODE: String? = null,
    val grower_SUB_CATG: String? = null,
    val id: Int? = null,
    val joint_ACCOUNT: String? = null,
    val loc_FTH_HUS_NAME: String? = null,
    val loc_RYOT_NAME: String? = null,
    val main_CODE: String? = null,
    val mazra_CODE: String? = null,
    val mem_SLIP: String? = null,
    val mem_YR: String? = null,
    val mobile: String? = null,
    val nominee_NAME: String? = null,
    val old_RYOT_CODE: String? = null,
    val pan_NO: String? = null,
    val parent_FAM_HEAD: String? = null,
    val parent_GROWER: String? = null,
    val parent_VILLAGE: String? = null,
    val ph: String? = null,
    val pin_CODE: String? = null,
    val r_RYOT_CODE1: String? = null,
    val r_RYOT_CODE2: String? = null,
    val r_RYOT_CODE3: String? = null,
    val relation_TYPE: String? = null,
    val religion_CODE: String? = null,
    val ryot_ADD1: String? = null,
    val ryot_ADD2: String? = null,
    val ryot_ADD3: String? = null,
    val ryot_ADD4: String? = null,
    val ryot_TYPE: String? = null,
    val sb_AC_NO: String? = null,
    val sl_CODE: String? = null,
    val state_CODE: String? = null,
    val supply_MODE: String? = null,
    val u_DT: String? = null,
    val u_ID: String? = null,
    val udc: String? = null,
    val udc_DT: String? = null,
    val uni_FTH_HUS_NAME: String? = null,
    val uni_RYOT_NAME: String? = null,
    val unique_GROWER_CODE: String,
    val unitCode: String? = null,
    val updt_BY: String? = null,
    val updt_DT: String? = null,
    val vehicle_CODE: String? = null,
    val verified_BY: String? = null,
    val verified_DT: String? = null,
    val verify_YN: String? = null,
    val village_CODE: String? = null
)